cache:
  paths:
    - node_modules/

stages:
  - init
  - deploy_qa
  - test_qa
  - deploy_prod

init:
  stage: init
  image: node:14.17
  script:
    - npm install

deploy_qa:
  image: node:14.17
  stage: deploy_qa
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/fitec-web-qa.git HEAD:master
    - echo "Deployed to qa server"
  environment:  
    name: qa
    url: https://fitec-web-qa.herokuapp.com/
  only:
    - develop

test_qa:
  stage: test_qa
  image: trion/ng-cli-e2e
  script:
    - ENV=qa npm run wdioTest
